const movies = [
  {
    id: 1,
    title: 'Kingsglaive',
    subtitle: 'Final Fantasy XV',
    storyline: "King Regis, who oversees the land of Lucis, commands his army of soldiers to protect the kingdom from the Niflheim empire's plans to steal the sacred crystal.",
    rating: 4.5,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLsxcDZHtby-MuCqaS43RWUxrVnVYCMvm86PSsFaa4uOyJD7UDf_vyZrdKMTDLBvKy6zw&usqp=CAU',
    bookmarked: true,
    genre: 'action',
  },
  {
    id: 2,
    title: 'Final Fantasy',
    subtitle: 'Spirits Within',
    storyline: 'A scientist makes a last stand on Earth with the help of a ragtag team of soldiers against an invasion of alien phantoms.',
    rating: 4.5,
    imagePath: 'https://i.ibb.co/WpJ3CV6/Final-Fantasy-Spirits-Within.jpg',
    bookmarked: false,
    genre: 'fantasy',
  },
  {
    id: 3,
    title: 'Ghost In The Shell',
    subtitle: 'Ghost In The Shell',
    storyline: 'A hacker known as the Puppet Master is hunted by a female cyborg cop and her partner. This film is a revised version of Ghost in the Shell (1995).',
    rating: 5,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzgf9gOBwPS1Wl_5zFuAWUNLCvm5sxtFArF49vBnZXekv_YIpGeGBlJQzi6XAoiv4S-7E&usqp=CAU',
    bookmarked: false,
    genre: 'comedy',
  },
  {
    id: 4,
    title: 'Appleseed Alpha',
    subtitle: 'Appleseed Alpha',
    storyline: "A young female soldier Deunan and her cyborg partner Briareos survive through the post World War 3 apocalyptic New York in search of human's future hope, the legendary city of Olympus.",
    rating: 3.8,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3knSCaBOfvPxSaGwWipqKP6TaAYMW9_Ch_D7G-AlfaHqM5Ipqkg87qOv4ez7tyjlUJRk&usqp=CAU',
    bookmarked: true,
    genre: 'action',
  },
  {
    id: 5,
    title: 'Resident Evil',
    subtitle: 'Vendetta',
    storyline: 'Chris Redfield enlists the help of Leon S. Kennedy and Rebecca Chambers to stop a death merchant, with a vengeance, from spreading a deadly virus in New York.',
    rating: 4.2,
    imagePath: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPPGZDM5prq7MLtCCuRojzU8jRNxyjtyzhaCjNHlZpQJhaomkpq4x5d0wCulqft2qldWY&usqp=CAU',
    bookmarked: true,
    genre: 'fantasy',
  },
];

export default movies;